<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $productNamAos = [
            [
                'productName' => 'Áo thun cổ tròn tay dài nam',
                'categoryID' => 10,
                'manufacturerID' => 1,
                'basePrice' => 200000.00,
                'description' => 'Áo thun nam chất liệu cotton, thoáng mát, phù hợp cho các hoạt động thể thao.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productName' => 'Áo thun cổ tròn tay ngắn nam',
                'categoryID' => 10,
                'manufacturerID' => 1,
                'basePrice' => 180000.00,
                'description' => 'Áo thun nam chất liệu cotton, thoáng mát, phù hợp cho mùa hè.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productName' => 'Áo thun cổ V nam',
                'categoryID' => 10,
                'manufacturerID' => 1,
                'basePrice' => 200000.00,
                'description' => 'Áo thun nam chất liệu cotton, thoáng mát, phù hợp cho mùa hè.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productName' => 'Áo thun cổ V thêu họa tiết nam',
                'categoryID' => 10,
                'manufacturerID' => 1,
                'basePrice' => 200000.00,
                'description' => 'Áo thun nam chất liệu cotton, thoáng mát, phù hợp cho mùa hè.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productName' => 'Áo thun cổ V phối đen trắng nam',
                'categoryID' => 10,
                'manufacturerID' => 1,
                'basePrice' => 200000.00,
                'description' => 'Áo thun nam chất liệu cotton, thoáng mát, phù hợp cho mùa hè.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productName' => 'Áo sơ mi kẻ caro nam',
                'categoryID' => 9,
                'manufacturerID' => 1,
                'basePrice' => 320000.00,
                'description' => 'Áo sơ mi kẻ caro nam nổi bật với họa tiết caro trẻ trung, thiết kế thanh lịch và dễ phối đồ. Chất liệu mềm mại, thoáng mát, mang lại cảm giác thoải mái khi mặc, phù hợp cho cả đi làm, đi học và dạo phố.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productName' => 'Áo sơ mi kaki tay ngắn nam',
                'categoryID' => 9,
                'manufacturerID' => 1,
                'basePrice' => 310000.00,
                'description' => 'Áo sơ mi kaki tay ngắn nam được thiết kế với kiểu dáng gọn gàng, trẻ trung và năng động. Chất liệu kaki mềm, thoáng mát, bền đẹp, mang lại cảm giác thoải mái khi mặc, phù hợp cho cả đi làm, đi chơi và các hoạt động hằng ngày.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productName' => 'Áo hoodie nam',
                'categoryID' => 11,
                'manufacturerID' => 1,
                'basePrice' => 420000.00,
                'description' => 'Áo hoodie nam có thiết kế trẻ trung, năng động với phom dáng thoải mái và mũ trùm tiện lợi. Chất liệu mềm mại, giữ ấm tốt nhưng vẫn thoáng khí, dễ dàng phối cùng quần jean, kaki hoặc jogger, phù hợp để mặc đi học, đi chơi hay dạo phố.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];
        $imageAoNams = [
            [
                'productID' => 1,
                'imageURL' => 'products/uHs25ukDYgfInMgjsRAVZAyzqQduqKWWWssxx2jT.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 1,
                'imageURL' => 'products/ygoyF594Ra9iTABATsiCXgWCfMgpeJVMALuO6Lvd.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 2,
                'imageURL' => 'products/EgGTRk8UFVVpvqxfrcEuH0gQFyDlpQtNl2635vqF.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 2,
                'imageURL' => 'products/KiMiCDWCFJFdmhzd9YYG0hUsAUPiinYEoQ7YTXIr.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 3,
                'imageURL' => 'products/xDemEDERQsSXQ3vH6aKyZc8rdv8avMsAdYHolf9Q.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 3,
                'imageURL' => 'products/PqmvYpmaCrcloFBTKD3kbLd6V92DIGhabD4tu88b.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 4,
                'imageURL' => 'products/CdEnVHSKmbN9SMI1AwKXxgBCbxcj4Je8oopHfCKh.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 4,
                'imageURL' => 'products/W7yFBvtHhCaLIdEE3k8sXwvJIsUA6m6qAT5CbeUh.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'productID' => 5,
                'imageURL' => 'products/jFRE9WASFbr0z7FLqNcCopfomqklxcraB9NL2tKL.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'productID' => 5,
                'imageURL' => 'products/082LetYfHWBL19m8YyIj5xJ77LM6ygeWqCMmsFsS.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 6,
                'imageURL' => 'products/FOLT7raSt12owhh7IeXVvjdllizsR7q8nncXMfv8.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'productID' => 7,
                'imageURL' => 'products/qB4TaUdqbdyJiS0DYMtdb6WaYa5jKr7mup4mXsJo.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 7,
                'imageURL' => 'products/NLAgU4iBd7cXeukjoaPlBnsyCOwZXuMdOjai8mIl.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 8,
                'imageURL' => 'products/CKQpS561Al9nJMQAD0snNBQMTsLFwR67SYgGss5C.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 8,
                'imageURL' => 'products/sr8KT9zCr1AzcE8WEdfSHPo1taHPqV36OpOyprv8.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 8,
                'imageURL' => 'products/wgdtab37hY542YF9rCmWvX4YY8SH5gjoDYDXQPoo.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];
        $productNamQuans = [
            [
                'productName' => 'Quần tây Tuytsi nam',
                'categoryID' => 16,
                'manufacturerID' => 1,
                'basePrice' => 370000.00,
                'description' => 'Quần tây Tuytsi nam được thiết kế với phom dáng đứng, ôm vừa vặn giúp tôn dáng và mang lại vẻ ngoài lịch lãm. Chất liệu bền đẹp, ít nhăn, thoáng mát, phù hợp mặc đi làm, dự tiệc hoặc kết hợp với nhiều phong cách thời trang khác nhau.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productName' => 'Quần kaki nam',
                'categoryID' => 16,
                'manufacturerID' => 1,
                'basePrice' => 420000.00,
                'description' => 'Quần kaki ống đứng nam sở hữu thiết kế đơn giản, phom dáng đứng gọn gàng, mang lại vẻ ngoài nam tính và hiện đại. Chất liệu kaki bền, thoáng khí, co giãn nhẹ, phù hợp để mặc đi làm, đi học hoặc dạo phố hằng ngày.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productName' => 'Quần jogger nam',
                'categoryID' => 16,
                'manufacturerID' => 1,
                'basePrice' => 350000.00,
                'description' => 'Quần jogger nam thiết kế hiện đại, thoải mái, phù hợp cho việc tập luyện hoặc mặc hàng ngày.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productName' => 'Áo sơ mi nam tay dài',
                'categoryID' => 9,
                'manufacturerID' => 1,
                'basePrice' => 420000.00,
                'description' => 'Áo sơ mi nam tay dài có thiết kế thanh lịch, phù hợp cho việc mặc đi làm hoặc các dịp trang trọng. Chất liệu cotton mềm mại, thoáng khí, dễ giặt và bảo quản.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];
        $imageQuanNams = [
            [
                'productID' => 9,
                'imageURL' => 'products/MmyMSQIE3q2x2F4zdyQszkNydQZ5zPK1l7XOtjuD.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 9,
                'imageURL' => 'products/xYI2mSt2fXiIruJJpsEcUEUwY7EhtxggRB6TrBEH.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 10,
                'imageURL' => 'products/O2AsD2eFT6p6GRixAYk0tjaMaEbffzj2WmMXP0Jd.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'productID' => 10,
                'imageURL' => 'products/4F9fL1eV1Zm79ObuCizTbfw1Y7PZlZ6oF876NEpj.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'productID' => 10,
                'imageURL' => 'products/OGYg3XChhAO6RdJou2vKJsVMQp7j9KPgEKj3dkPB.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 11,
                'imageURL' => 'products/3T0ZqSP5Bxh5s81c8yPegByMEG7nRnWbbsXujcJ0.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'productID' => 12,
                'imageURL' => 'products/Li8k50F32cYNFE3AfuqdpH9wBcehWZ4ozR5wvwyh.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 12,
                'imageURL' => 'products/mFfT0JY8jL3cGalWWfTVu6V4ht77ZwWqQVrJolnp.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'productID' => 12,
                'imageURL' => 'products/pBjnm0L1qsbDZKhyZhYr3BpcONsHOIQO0oyT4NPb.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];
        $productNuAos = [
            [
                'productName' => 'Áo thun cổ tròn họa tiết nữ',
                'categoryID' => 12,
                'manufacturerID' => 1,
                'basePrice' => 450000.00,
                'description' => 'Thiết kế mang tinh thần thanh lịch hiện đại với gam trắng tinh khôi cùng bề mặt vải dệt nổi họa tiết lông vũ mềm mại. Phom áo dáng ngắn gọn gàng giúp tôn tỷ lệ cơ thể, đồng thời tạo điểm nhấn tinh tế khi phối cùng chân váy hoặc quần cạp cao.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productName' => 'Áo thun cổ V kẻ sọc nữ',
                'categoryID' => 12,
                'manufacturerID' => 1,
                'basePrice' => 420000.00,
                'description' => 'Áo thun nữ cổ chữ V có thiết kế đơn giản, tôn dáng với phần cổ chữ V thanh lịch, mang đến vẻ ngoài nữ tính và hiện đại. Chất liệu mềm mại, thoáng mát, thấm hút mồ hôi tốt, phù hợp để mặc hằng ngày, đi học, đi làm hoặc dạo phố.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productName' => 'Áo thun ôm cổ đan chéo nữ',
                'categoryID' => 12,
                'manufacturerID' => 1,
                'basePrice' => 390000.00,
                'description' => 'Áo thun ôm cổ đan chéo nữ sở hữu thiết kế ôm dáng tôn lên đường nét cơ thể cùng chi tiết cổ đan chéo nổi bật, tạo điểm nhấn thanh lịch và quyến rũ. Chất liệu co giãn, mềm mại và thoáng mát, mang lại cảm giác thoải mái, phù hợp để mặc đi làm, đi chơi hoặc dạo phố.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productName' => 'Áo thun tay dài nữ',
                'categoryID' => 12,
                'manufacturerID' => 1,
                'basePrice' => 400000.00,
                'description' => 'Áo thun tay dài nữ có thiết kế đơn giản, thanh lịch với phom dáng vừa vặn, mang đến cảm giác thoải mái và dễ mặc. Chất liệu mềm mại, co giãn tốt, thấm hút mồ hôi hiệu quả, phù hợp để mặc hằng ngày, đi học, đi làm hoặc dạo phố trong mọi thời tiết.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productName' => 'Quần tây ống suông nữ',
                'categoryID' => 21,
                'manufacturerID' => 1,
                'basePrice' => 440000.00,
                'description' => 'Quần tây ống suông nữ có thiết kế đơn giản, thanh lịch với phom dáng vừa vặn, mang đến cảm giác thoải mái và dễ mặc. Chất liệu mềm mại, co giãn tốt, thấm hút mồ hôi hiệu quả, phù hợp để mặc hằng ngày, đi học, đi làm hoặc dạo phố trong mọi thời tiết.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productName' => 'Quần tây xếp ly nữ',
                'categoryID' => 21,
                'manufacturerID' => 1,
                'basePrice' => 450000.00,
                'description' => 'Quần tây xếp ly nữ có thiết kế đơn giản, thanh lịch với phom dáng vừa vặn, mang đến cảm giác thoải mái và dễ mặc. Chất liệu mềm mại, co giãn tốt, thấm hút mồ hôi hiệu quả, phù hợp để mặc hằng ngày, đi học, đi làm hoặc dạo phố trong mọi thời tiết.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productName' => 'Chân váy bút chì nữ',
                'categoryID' => 22,
                'manufacturerID' => 1,
                'basePrice' => 450000.00,
                'description' => 'Chân váy bút chì nữ có thiết kế đơn giản, thanh lịch với phom dáng vừa vặn, mang đến cảm giác thoải mái và dễ mặc. Chất liệu mềm mại, co giãn tốt, thấm hút mồ hôi hiệu quả, phù hợp để mặc hằng ngày, đi học, đi làm hoặc dạo phố trong mọi thời tiết.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productName' => 'Chân váy chữ A dáng ngắn nữ',
                'categoryID' => 23,
                'manufacturerID' => 1,
                'basePrice' => 450000.00,
                'description' => 'Chân váy chữ A dáng ngắn nữ có thiết kế đơn giản, thanh lịch với phom dáng vừa vặn, mang đến cảm giác thoải mái và dễ mặc. Chất liệu mềm mại, co giãn tốt, thấm hút mồ hôi hiệu quả, phù hợp để mặc hằng ngày, đi học, đi làm hoặc dạo phố trong mọi thời tiết.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productName' => 'Chân váy xòe họa tiết nữ',
                'categoryID' => 24,
                'manufacturerID' => 1,
                'basePrice' => 480000.00,
                'description' => 'Chân váy xòe họa tiết nữ có thiết kế đơn giản, thanh lịch với phom dáng vừa vặn, mang đến cảm giác thoải mái và dễ mặc. Chất liệu mềm mại, co giãn tốt, thấm hút mồ hôi hiệu quả, phù hợp để mặc hằng ngày, đi học, đi làm hoặc dạo phố trong mọi thời tiết.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'productName' => 'Chân váy xòe nữ',
                'categoryID' => 24,
                'manufacturerID' => 1,
                'basePrice' => 470000.00,
                'description' => 'Chân váy xòe nữ có thiết kế đơn giản, thanh lịch với phom dáng vừa vặn, mang đến cảm giác thoải mái và dễ mặc. Chất liệu mềm mại, co giãn tốt, thấm hút mồ hôi hiệu quả, phù hợp để mặc hằng ngày, đi học, đi làm hoặc dạo phố trong mọi thời tiết.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'productName' => 'Chân váy ren nữ',
                'categoryID' => 24,
                'manufacturerID' => 1,
                'basePrice' => 470000.00,
                'description' => 'Chân váy ren nữ có thiết kế đơn giản, thanh lịch với phom dáng vừa vặn, mang đến cảm giác thoải mái và dễ mặc. Chất liệu mềm mại, co giãn tốt, thấm hút mồ hôi hiệu quả, phù hợp để mặc hằng ngày, đi học, đi làm hoặc dạo phố trong mọi thời tiết.',
                'imageID' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];
        $imageAoNus = [
            [
                'productID' => 13,
                'imageURL' => 'products/8tmBhbBwAcNJxKZ8e0VNQzk5TYgBQLeFcooDGPg6.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 14,
                'imageURL' => 'products/B82GOEi2UYxdruRXPtGgfRpDb2eKlnBzPrQ8NIwj.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 14,
                'imageURL' => 'products/5iNj9yCriG34FsMEbJj0ouByunlvykDwWTIXX7nR.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 15,
                'imageURL' => 'products/ILPprKUkKmS6MdKJUyuISysx8OypgTXw9fyzNgmK.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'productID' => 15,
                'imageURL' => 'products/MPWaERUE5VYXgOJMFm4IH7tLZYP2GDa9GrAHVrUm.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 16,
                'imageURL' => 'products/exLguaL2FxgCisGpFzqmhucTUoPeEbjuiHT3IVa9.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 16,
                'imageURL' => 'products/MQWWoJaCMH5vcLb69Fg1xnNa5BJmK9zmqqg0Vvst.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'productID' => 17,
                'imageURL' => 'products/ZVYL2iHpxsBvBLkXuVowpykboDIkj086ee8Ohzwe.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'productID' => 17,
                'imageURL' => 'products/1C7pqP49LV5o1cDMo2WY3jxHAvUzMckwmLiUekrh.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => 18,
                'imageURL' => 'products/BZbd8nAcH7mO8GJgm1T0jSDEmXq72uzCYBYa5mpS.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'productID' => 18,
                'imageURL' => 'products/OXq2xf5dyeLwKsGULqApps2LaSGidjJta0ADI4Qn.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'productID' => 19,
                'imageURL' => 'products/8fb4baf6de28a7dd548e22b4c6b49e63.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'productID' => 19,
                'imageURL' => 'products/3bd28e06b6494d7ab84fa36bf0d987cc.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'productID' => 19,
                'imageURL' => 'products/1c4df198440320bf8b39c2c9ce812368.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'productID' => 19,
                'imageURL' => 'products/f37a03224eb4bed68ea60b46e7003683.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'productID' => 20,
                'imageURL' => 'products/60aee56383051aa7cb31b7e31fc9ffa6.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'productID' => 20,
                'imageURL' => 'products/f8709fd4b88409bbb0127e7bd0683a6b.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'productID' => 21,
                'imageURL' => 'products/91f359dbc78d04a9269882b931ce0c18.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'productID' => 21,
                'imageURL' => 'products/3f4199dc746c3b6d3d3e970216d9824d.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'productID' => 22,
                'imageURL' => 'products/fe6b5f6e02630bc3ccf494e14c874fc6.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'productID' => 22,
                'imageURL' => 'products/fe6b5f6e02630bc3ccf494e14c874fc6.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'productID' => 23,
                'imageURL' => 'products/72811614a2790d97a864fa80abe32b07.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'productID' => 23,
                'imageURL' => 'products/1c0b627ac242fa1ae1f62273ab2029c7.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'productID' => 23,
                'imageURL' => 'products/c25b3babd7b4c3aa49bff0152a873cee.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ];
        DB::table('products')->insert($productNamAos);
        DB::table('product_images')->insert($imageAoNams);
        DB::table('products')->insert($productNamQuans);
        DB::table('product_images')->insert($imageQuanNams);
        db::table('products')->insert($productNuAos);
        db::table('product_images')->insert($imageAoNus);
    }
}
